#!/bin/bash

# colors
white="\033[1;37m"
yellow="\033[1;33m"
red="\033[1;31m"
green="\033[1;32m"
cyan="\033[1;36m"
reset="\033[0m"

printf "${yellow}Validating commit message...${reset} 🚀\n"

# Get the commit message
commit_msg="$(cat $1)"

# Regex to match the desired commit message format
regex="^(feat|fix|docs|chore|build|cli)(\([a-z0-9\-]+\))?(!)?: .+"

# Check if the commit message matches the regex
if ! echo "$commit_msg" | grep -Eq "$regex"; then
  printf "${red}ERROR:${white} Commit message does not follow the correct format. ${reset}\n"  
  echo "Please use a format similar to following formats:"
  echo "  chore: chore description"
  echo "  docs(api): api docs change description"
  echo "  feat(api)!:  api feature breaking change description"
  echo "  fix!: breaking change bugfix description"
  echo "=========================================================================="
  printf "|| For more info visit: ${cyan}https://www.conventionalcommits.org/en/v1.0.0/${reset}  ||\n"
  echo "=========================================================================="
  exit 1
fi

printf "${green}Commit message is valid. Proceeding with commit. ${reset} ✨\n"