#!/bin/sh

npm run validate

# Array of special branch names that are allowed to be pushed
allowed_branches=("main" "dev")

# Regular expression for validating username-issuenumber format
branch_name_regex="^[a-zA-Z0-9]+(-[a-zA-Z0-9]+)*-[0-9]+$"

# Get the current branch name
branch_name=$(git rev-parse --abbrev-ref HEAD)

# Check if the branch name is in the allowed branches array
for allowed_branch in "${allowed_branches[@]}"; do
  if [ "$branch_name" = "$allowed_branch" ]; then
    echo "Branch '$branch_name' is allowed. Proceeding with push. "
    exit 0
  fi
done

# Check if the branch name matches the regex
if [[ ! "$branch_name" =~ $branch_name_regex ]]; then
  echo "Error: Branch name '$branch_name' does not match the required format 'username-issuenumber'."
  exit 1
fi

# Check if the username part is a valid GitHub username
username=$(echo "$branch_name" | cut -d'-' -f1)
if [[ ! "$username" =~ ^[a-zA-Z0-9]+(-[a-zA-Z0-9]+)*$ ]]; then
  echo "Error: Username part '$username' is not a valid GitHub username."
  exit 1
fi

echo "Branch name is valid. Proceeding with push."