#!/bin/bash

# colors
white="\033[1;37m"
yellow="\033[1;33m"
red="\033[1;31m"
green="\033[1;32m"
cyan="\033[1;36m"
reset="\033[0m"

printf "${yellow} Validating branch contents... ${reset} 🚀\n"

npm run validate

printf "${green}Branch contents are valid. Proceeding with push. ${reset} ✨\n"