#!/bin/bash

# colors
white="\033[1;37m"
yellow="\033[1;33m"
red="\033[1;31m"
green="\033[1;32m"
cyan="\033[1;36m"
reset="\033[0m"

printf "${yellow}Validating commit changes...${reset}\n"

npx lint-staged

printf "${green}Commit changes are valid. ${reset} ✨ \n"